### ISSUE TITLE
Feature Request: MinuteClock, HourClock and DayClock service

### ISSUE THREAD

**Issue by arthur5005** [tzellman/ember-stopwatch#75]
It would be nice if there were other clock services that had `minute`, `hour` and `day` resolutions for the update interval of the `time` property. This would prevent invoking the template engine for re-render checking. 

`MinuteClock`
`HourClock`
`DayClock`

perhaps?

I don't mind writing them myself, but really I'm just copy-pasting what's in your clock service to get different resolutions.

**Comment by arthur5005** [comment]
Gave it some more thought and opened a PR to add time division props to both the util and the service. 

Added some basic tests. 

Let me know what you think.

**Comment by tzellman** [comment]
Merged in #76
